### ISSUE TITLE
Documentation of module file

### ISSUE THREAD

**Issue by canatella** [SidharthArya/modules.el#2]
Hello, interesting project, thank you for taking the time to publish it. 

To my question: what should a module file look like ? Just a `module-name.el` file ? Does it need to `(provide 'module-name)` ? A small example in the readme could help there.

Thank you!

**Comment by SidharthArya** [comment]
Hi, Sorry about the late reply. Module file is just a simple file containing some elisp. So `module-name.el` file should suffice. There is no need to `(provide 'module-name)`. There are no rules at all, as to how you write your module. The only constraint of having dependent modules can be satisfied with: 
`(modules-load '(space separated list of modules))`
Thank you for your suggestion. I really need to write a more elaborate documentation. I have added an example file.
de2357e

**Comment by canatella** [comment]
Thank you, that is all I needed :) Feel free to close this issue.
