### ISSUE TITLE
Add MELPA

### ISSUE THREAD

**Issue by conao3** [SidharthArya/modules.el#3]
Hi!
I found this package and this package and it seems a very awesome package.
How about add MELPA? is this needed name change maybe?

**Comment by SidharthArya** [comment]
Hi! First of all, you write amazing packages, so thank you. 
Sorry about the late reply. I added a pull request and withdrew it later since i was having doubts about it being all that helpful. It does need a name change i guess, to be added to melpa. 
Do you have any suggestions regarding the name change?

**Comment by conao3** [comment]
Naming is a difficult thing to do.
I'm thinking of adding a keyword for this package at [leaf-keywords](https://github.com/conao3/leaf-keywords.el) in the future, so a one-word name for it would be good.
I've googled some time, but there doesn't seem to be a good analogy for **module**.
We may need a completely different idea for naming it.

**Comment by SidharthArya** [comment]
I see. 
My idea of naming it modules was the user modularizing his/her config file into various reusable, functional bits of code, which can then be plugged in.  
Maybe `modular` ? Or something else?
Anything you suggest will be fine though.

**Comment by conao3** [comment]
Yes, `modular` is better. but...
I can't suggest about naming, but there has to be a better name for it.

**Comment by SidharthArya** [comment]
@conao3 Is this okay now ??

**Comment by conao3** [comment]
I think good!

**Comment by SidharthArya** [comment]
@conao3 My package has been merged to melpa.
https://github.com/melpa/melpa/pull/7083

**Comment by conao3** [comment]
Awesome, I'll try it!
