### ISSUE TITLE
Update 'Example Module' in README.org 

### ISSUE THREAD

**Issue by alex-a-soto** [SidharthArya/modules.el#4]
SidharthArya,

Thank you for creating modular-config! I'm in the process of transitioning away from Doom to my own configuration and have found it helpful, particularly in comparison to Emacs built-in require/provide system. 

**Issue:**

While reading the documentation I noticed that in the README.org in the `Example Module` section: 

- it's using `modular-config-modules-load` and rather should be `modular-config-load-modules`.

Thank you again for creating the package!

**Comment by SidharthArya** [comment]
Thank you for pointing this out.
Originally the package was named modules.el and it had different function names. I will make the changes. Sorry for the inconvenience caused :)
https://github.com/SidharthArya/modular-config.el/commit/c0a6d3dac1aa176deb8417c77dfeac06e9f18e1fl

And thank you for using my package. :)
